# Use root/example as user/password credentials
version: '3.1'

services:

  predict-api:
    build: .
    ports:
      - "127.0.0.1:6788:8080"
    restart: unless-stopped
    volumes: 
      - ./docker/log:/usr/src/app/log